### ISSUE TITLE
MACSE pseudogene removal workflow???

### ISSUE THREAD

**Issue by naurasd** [alexpiper/HemipteraMetabarcodingMS#1]
Hey guys,

I really appreciate the detailled documentation and workflow you made publicly available. Great opportunity to learn from. However, I couln't find any scripts you guys used for MACSE pseudogene removal. Could you direct me to the corresponding workflow? According to your manuscript, this was supposed to be performed post taxonomic classification and pre index switching analysis, but I couldn't really find anything in your documentation.

Cheers
Nauras

**Comment by alexpiper** [comment]
Ahh yes, that does seem to be missing rom the documentation, i will fix this.

The code used (following creation of phyloseq object) was:

    # Write out fasta of COI sequences from R 
    ps <- readRDS("output/rds/ps_rdp.rds")
    ps_coi <- subset_taxa(ps, loci == "COI-Eukaryota")
    coi_seqs <- DNAStringSet(colnames(get_taxa(ps_coi)))
    names(coi_seqs) <- colnames(get_taxa(ps_coi))
    writeXStringSet(coi_seqs, filepath = "output/coi_seqs.fasta", width=1000)
    
    # Align using MACSE (command line or GUI app)
    java -jar macse.jar -prog alignSequences -gc_def 5 -seq coi_seqs.fasta
    
    # Read MACSE AA alignment back into R
    macse_aligned <- readAAStringSet("output/coi_seqs_AA.fasta")
    
    # Check for stop codons. 
    # Note: only count internal stop codons as primer removal can cause stop codons at start and end
    is_pseudogene <- sapply(macse_aligned, function(x){
       int_codons <- x %>% 
        str_remove("^!") %>% # Remove stop codon at start of seq
        str_remove("![-]*$") # Remove any stop codon at end of seq
      # Detect if sequence contains internal stop codons
      #str_detect(int_codons, "!") 
    })
    
    pseudogene_seqs <- names(macse_aligned)[is_pseudogene]
    
    # Remove pseudogene seqs from phyloseq object
    ps_pruned <- prune_taxa(taxa_names(ps)[!taxa_names(ps) %in% pseudogene_seqs], ps)
    
    # Write out pruned phyloseq object
    saveRDS(ps_pruned, "output/rds/ps_pruned.rds")


Cheers,
Alex

**Comment by naurasd** [comment]
Thanks @alexpiper , appreciate your help.

Nauras
