### ISSUE TITLE
README missing URL/DOI for published manuscript

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#2]
The README starts:

> This repository hosts the R based reproducible workflow that performed the analyses presented for the manuscript "Developing a non-destructive metabarcoding protocol for detection of pest insects in bulk trap catches" by J. Batovska, A.M. Piper, I. Valenzuela, J.P. Cunningham & M.J. Blacket

I suggest adding at least the DOI: https://doi.org/10.1038/s41598-021-85855-6

**Comment by alexpiper** [comment]
Good point, ive added the DOI as well as the previously missing SRA link to the raw data.

**Comment by peterjc** [comment]
I see it - 89bb4f456b0f428dd796763f49fc43593081e7cd - lovely, thank you.
