### ISSUE TITLE
ENA raw data incomplete?

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#3]
Thank you for sharing the supplementary data in a GitHub repository like this.

https://www.ebi.ac.uk/ena/browser/view/PRJNA716058?show=reads currently has 30 samples, picking columns and exporting as TSV can gives a table like this, which I have sorted to match ``Sample_info.csv`` and broken up into blocks.

```
run_accession  library_name  read_count  run_alias                             sample_alias
SRR14022282    Trap_1        1759819     Trap-1_S1_L001_R1_001.fastq.gz        Trap-1
SRR14022281    Trap_2        1127739     Trap-2_S2_L001_R1_001.fastq.gz        Trap-2
SRR14022280    Trap_3        2422054     Trap-3_S3_L001_R1_001.fastq.gz        Trap-3
SRR14022279    Trap_4        742893      Trap-4_S4_L001_R1_001.fastq.gz        Trap-4
SRR14022278    Trap_5        3437292     Trap-5_S5_L001_R1_001.fastq.gz        Trap-5
SRR14022277    Trap_6        697389      Trap-6_S6_L001_R1_001.fastq.gz        Trap-6
SRR14022276    Trap_7        2853448     Trap-7_S7_L001_R1_001.fastq.gz        Trap-7
SRR14022275    Trap_8        2196646     Trap-8_S8_L001_R1_001.fastq.gz        Trap-8
SRR14022274    Trap_9        2065455     Trap-9_S9_L001_R1_001.fastq.gz        Trap-9
SRR14022273    Trap_10       2445993     Trap-10_S10_L001_R1_001.fastq.gz      Trap-10

SRR14022295    100_1         478705      100-Pool-1_S1_L001_R1_001.fastq.gz    100-Pool-1
SRR14022294    100_2         737998      100-Pool-2_S2_L001_R1_001.fastq.gz    100-Pool-2
SRR14022283    100_3         950692      100-Pool-3_S3_L001_R1_001.fastq.gz    100-Pool-3
SRR14022272    100_4         634017      100-Pool-4_S4_L001_R1_001.fastq.gz    100-Pool-4
SRR14022271    100_5         1817929     100-Pool-5_S5_L001_R1_001.fastq.gz    100-Pool-5

SRR14022293    500_1         647776      500-Pool-1_S6_L001_R1_001.fastq.gz    500-Pool-1
SRR14022292    500_2         1908370     500-Pool-2_S7_L001_R1_001.fastq.gz    500-Pool-2
SRR14022291    500_3         923807      500-Pool-3_S8_L001_R1_001.fastq.gz    500-Pool-3
SRR14022290    500_4         572779      500-Pool-4_S9_L001_R1_001.fastq.gz    500-Pool-4
SRR14022289    500_5         807060      500-Pool-5_S10_L001_R1_001.fastq.gz   500-Pool-5

SRR14022288    1000_1        855997      1000-Pool-1_S11_L001_R1_001.fastq.gz  1000-Pool-1
SRR14022287    1000_2        1068715     1000-Pool-2_S12_L001_R1_001.fastq.gz  1000-Pool-2
SRR14022286    1000_3        1773647     1000-Pool-3_S13_L001_R1_001.fastq.gz  1000-Pool-3
SRR14022285    1000_4        1198812     1000-Pool-4_S14_L001_R1_001.fastq.gz  1000-Pool-4
SRR14022284    1000_5        1423279     1000-Pool-5_S15_L001_R1_001.fastq.gz  1000-Pool-5

SRR14022270    250_1         1845819     250-Pool-1_S6_L001_R1_001.fastq.gz    250-Pool-1
SRR14022269    250_2         2037475     250-Pool-2_S7_L001_R1_001.fastq.gz    250-Pool-2
SRR14022268    250_3         1631700     250-Pool-3_S8_L001_R1_001.fastq.gz    250-Pool-3
SRR14022267    250_4         2501145     250-Pool-4_S9_L001_R1_001.fastq.gz    250-Pool-4
SRR14022266    250_5         1632786     250-Pool-5_S10_L001_R1_001.fastq.gz   250-Pool-5
```

So, 10 trap samples, and then four sets of five mock community pools.

However, it appears there should be 35 samples - e.g. based on https://github.com/alexpiper/HemipteraMetabarcodingMS/blob/master/sample_data/Sample_info.csv which has two rows per sample as it lists both R1 and R2 separately.

Matching the two up is complicated as the field order is inconsistent, for example we have ``500-Pool-5`` in the ENA metadata versus ``Pool-05-100`` in ``Sample_info.csv`` (different order, and replicate number with a leading zero). This applies to the R1 and R2 filenames in the two tables as well as the sample names/aliases.

Anyway, the count discrepancy is the ENA with 30 samples only has a single set for Pool 250, whereas ``Sample_info.csv`` has two sets of five for Pool 250 labelled with a U or C, probably meaning Unique or Combinatorial in reference to the indexing, quoting the paper,

> *To investigate the impacts of index switching on the sequencing data, the 250 mock community libraries (pools 1–5) were prepared using both non-unique (combinatorial) and unique dual indexes. The remaining three sets of 5 mock communities (100, 500, and 1000) as well as field trap samples were prepared using unique dual indexes.*

i.e. There appears to be a set of five samples for one of the 250 Pools missing?

**Comment by alexpiper** [comment]
Thanks for noticing these issues, I will flag them with the author who uploaded the files, but as they are on leave for the next 2 weeks it might take a little bit of time to correct the SRA submission.

In the meantime, i can share the missing files through a temporary hosting service if you require?

**Comment by peterjc** [comment]
Adding the missing five files to the SRA would be most welcome, and I agree asking the same person to do it is wise, even if it will take longer with them being on leave.

Direct sharing of the data in the short term might be useful, yes please. Link by email if you'd prefer not to post it on GitHub?

For me and anyone else curious to repeat your analysis, it would be very helpful if a mapping between the ENA accession and the sample / filenames used in this repository was provided. Editing the ENA metadata would be one way, but tricky. Adding or updating a CSV file on this repository would probably be easier, and git would give an audit trial.

If you were to work on that mapping, I would also like to see the Illumina plate indicated (e.g. plate 1, plate 2, and plate 3). I can make some good guesses based on the filename suffix like ``_S15_L001_R1_001.fastq.gz`` but better to be explicit. Why? Sometimes it is useful to set thresholds on a plate by plate basis.

**Comment by alexpiper** [comment]
I have added extra columns to the `Sample_info.csv` file that show the mapping to the SRA accession numbers, as well as the plate/flow cell each sample was included on https://github.com/alexpiper/HemipteraMetabarcodingMS/commit/9e0454aa09d1b69896273e53619429e16ef96901 .

Ive also uploaded all the original fastq files (including the 5 missing samples) to [zenodo](https://doi.org/10.5281/zenodo.5171623). These 5 samples will also be uploaded to SRA once the author is back from leave. 

While confirming that the zenodo fastq files matched what is on SRA, i realised that SRA strips the fastq headers from all uploads. As the index switching calculation relies upon the per-read index information normally contained within these fastq headers, this unfortunately means that step is only reproducable using the fastq files in the zenodo repository. Otherwise the results of that calculation (the determined.txt and undetermined.txt files) are included in the demultiplexing directory within this github repository.

**Comment by peterjc** [comment]
The additions to ``Sample_info.csv`` look good (pending adding the missing five SRA accessions).

Thanks for the heads up about index switching in these FASTQ files with the original files on Zenodo vs those processed by the ENA.

**Comment by alexpiper** [comment]
The 5 missing samples have now been added to the BioProject (accessions SRR16944108-SRR16944112) and the sample_info.csv file has been updated e7765883929b5687301f0c883338daec333b3524 

Sorry for how long this took.
