### ISSUE TITLE
Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#4]
I am trying to run the R code provide in ``hemiptera_metabarcoding.Rmd`` using ``knitr`` to extract it as an R script, and run it:

```
$ git clone https://github.com/alexpiper/HemipteraMetabarcodingMS.git
...
$ cd HemipteraMetabarcodingMS
$ Rscript -e "f <- tempfile(); knitr::purl('hemiptera_metabarcoding.Rmd', output = f); source(f, echo = TRUE)"
...
Loading required package: ggtree
Loading required package: insect
     dada2   phyloseq        ips   DECIPHER data.table  tidyverse Biostrings 
      TRUE      FALSE      FALSE      FALSE      FALSE      FALSE       TRUE 
 ShortRead     scales stringdist  patchwork      psadd     ggpubr     seqinr 
      TRUE       TRUE      FALSE      FALSE      FALSE      FALSE      FALSE 
     limma    ggforce    viridis  data.tree     ggtree     insect 
     FALSE      FALSE      FALSE      FALSE      FALSE      FALSE 

> source("scripts/helper_functions.R")

> runs <- dir("data/", pattern = "run")

> filtered_out <- list()

> for (i in seq(along = runs)) {
+     path <- paste0("data/", runs[i])
+     filtpath <- file.path(path, "filtered")
+     fastqFs <- sort(list.files .... [TRUNCATED] 
Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'
Calls: source ... withVisible -> eval -> eval -> filterAndTrim -> unlist
In addition: There were 31 warnings (use warnings() to see them)
Execution halted
```

I had to install assorted R dependencies to get this far (using ``$ conda install install r r-markdown r-knitr bioconductor-dada2``). Versions present:

```
$ conda list | grep -E "^(r |r-markdown|r-knitr|bioconductor-dada2)"
bioconductor-dada2        1.22.0            r41hb890f52_2    bioconda
r                         4.1             r41hd8ed1ab_1004    conda-forge
r-knitr                   1.40              r41hc72bb7e_0    conda-forge
r-markdown                1.1               r41h28b5c78_1    conda-forge
```

From the context, I guess this is an data2 problem, and https://github.com/benjjneb/dada2/issues/659 and https://github.com/benjjneb/dada2/issues/959 are similar in terms of the error. The later suggests an empty list of files is to blame?

Is that correct? How does it expect the files to be named? e.g. Would ``SRR*.fastq.gz`` work?

**Comment by alexpiper** [comment]
Yep i think an empty list of files is to blame here, probably because the pattern in the `list.files` call isnt matching the current fastq names.

There is a bash script: scripts/download_SRA_fastqs.sh which downloads and renames the SRR*.fastq.gz files from SRA to the format that this analysis pipeline expects.

**Comment by peterjc** [comment]
My R was never that strong, a human friendly message would be nicer. Still, anyone else hitting this error should find this issue and know how to fix it.

I can try this with the FASTQ files if needed - it took a bit of trial and error but I was able to jump ahead to the figure generation in the end.

Thank you :)
