### ISSUE TITLE
object 'psmock' not found

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#5]
I've been trying to run a subset of the R code in ``hemiptera_metabarcoding.Rmd`` sufficient to regenerate Figure 3. This has required assorted ``library(...)`` calls and also running the "R Assign Taxonomy" section before getting to "r Figure 3 - merged figure".

The code is now failing here: ``subset_samples(sample_names(psmock)!=rm_c1) %>%``

Searching the file this is the only occurrence of ``psmock``, the variable is never setup. Older versions did, e.g.

```R
# Plot Fig1b - all 3 loci merged
psmock <- ps_filtered
```

I thinks the error crept in during fea4f83ee281d2c50391548f7827ff60031af1d1 and the simplest fix is to replace ``psmock`` with ``ps_filtered``?

**Comment by alexpiper** [comment]
Thanks for noticing it, yep its a holdover from a previous change. In https://github.com/alexpiper/HemipteraMetabarcodingMS/commit/e7b050a572afb80ff8fda5a52689c7777db994e0 ive replaced it with ps_filtered
