### ISSUE TITLE
Including output/rds/ps_pruned.rds in repository?

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#6]
I am hoping to reproduce the Figures without repeating the entire analysis. Right now I am stuck on needing intermediate file ``output/rds/ps_pruned.rds`` which is not in the repository.

If the file is small, would it be reasonable to include it in the repository?

**Comment by peterjc** [comment]
Partial success: I managed to get Figure 3 to run without going back to the FASTQ files (although it required a lot of trial-and-error fixing missing R dependencies, and the species key does not look pretty).

**Comment by alexpiper** [comment]
The ps_pruned.rds and ps_filtered.rds files should now be included with commit f4f2966

**Comment by peterjc** [comment]
Thank you!
