### ISSUE TITLE
False positives/negatives on Figure 3

### ISSUE THREAD

**Issue by peterjc** [alexpiper/HemipteraMetabarcodingMS#7]
I am currently struggling to run the R code to generate Figure 3 (see other recently opened issues), but from reading it cannot see how it annotated the false negatives (-) and false positives (+):

* https://github.com/alexpiper/HemipteraMetabarcodingMS/blob/master/Figures/Fig3_Mock_Communities.pdf
* https://github.com/alexpiper/HemipteraMetabarcodingMS/blob/master/Figures/Fig3_Mock_Communities.png

![](https://github.com/alexpiper/HemipteraMetabarcodingMS/raw/master/Figures/Fig3_Mock_Communities.png)

Where those finishing touches added by hand? If so, a comment in the code about this would be appreciated.

The final version in the paper and here (repository links below) appears to differ only in the addition of asterisks to the mock sample names:

* https://github.com/alexpiper/HemipteraMetabarcodingMS/blob/master/Figures/Final/Fig3_Mock_Communities.pdf
* https://github.com/alexpiper/HemipteraMetabarcodingMS/blob/master/Figures/Final/Fig3_Mock_Communities.png

![](https://github.com/alexpiper/HemipteraMetabarcodingMS/raw/master/Figures/Final/Fig3_Mock_Communities.png)

I presume the asterisks were added manually?

**Comment by peterjc** [comment]
I also don't see how the sample captions were done in R.

I could hack this by converting the ``pool_comp`` values 1.1 to 4.5 as follows:

```R
require(comprehenr)
#pool_comp <- df_exp$pool_comp
#Sample data:
pool_comp <- c(1.1, 1.2, 1.3, 1.4, 2.1, 5.4)
to_vec(for(px in pool_comp) paste(c("100", "250", "500", "1000")[round(10*(px-floor(px)))], "Pool", floor(px)))
```

**Comment by alexpiper** [comment]
Hi Peter,

Sorry that youve had trouble getting the code to run. This project was from quite early in my grad school journey and i was still learning about reproducable analysis.

For all the figures there was a little bit of editing outside of R which was done to make them more presentable or in response to reviewer comments. The + - captions and changes in the sample names was done in Inkscape after they were exported from R.

Ive added some notes to the code in https://github.com/alexpiper/HemipteraMetabarcodingMS/commit/e7b050a572afb80ff8fda5a52689c7777db994e0

**Comment by peterjc** [comment]
That's great - there may be things you'd have done differently in hindsight, but this repository makes your paper far better than most in the reproducibility stakes. Thank you!
